---
title: "PAR Xtreem"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## parXtreem

This is for managing and understanding your PAR Odyssey Xtreem data

## Requirements

  + [R v4+](https://www.r-project.org/)
  + [dplyr](https://CRAN.R-project.org/package=dplyr)
  + [readr](https://CRAN.R-project.org/package=readr)
  + [stringr](https://CRAN.R-project.org/package=stringr)
  + [ggplot2](https://CRAN.R-project.org/package=ggplot2)

## Installation

```
remotes::install_github("rfrancolini/parXtreem")
```

## Read Example Data

```{r example}
library(parXtreem)
x <- read_parXtreem()
x
```

## Draw Example Plot

```{r parplot}
parplot_x <- draw_plot(x)
parplot_x
```

## Read Example Data with Defined Start/Stop Dates

```{r exampleStartStop}
ss <- as.POSIXct(c("2021-05-20", "2021-06-01"), tz = "UTC")
xud <- read_parXtreem(clipped = "user", startstop = ss)
xud
```

## Draw Example Plot User Defined Start/Stop Dates

```{r parplot_ud}
parplot_xud <- draw_plot(xud)
parplot_xud
```

## Read Example Data Without Clipping Data

```{r exampleNA}
xna <- read_parXtreem(clipped = "none")
xna
```

## Draw Example Plot Without Clipping Data

```{r parplot_na}
parplot_na <- draw_plot(xna)
parplot_na
```
